steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/ratelimiter:$SHORT_SHA', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/ratelimiter:$SHORT_SHA' ]
- name: 'gcr.io/dd-dev-exam/terraform:0.12.20'
  args: ['init','-backend-config=bucket=$PROJECT_ID-ratelimiter-terraform', './terraform']
  env:
    - TF_VAR_project_id=$PROJECT_ID
- name: 'gcr.io/dd-dev-exam/terraform:0.12.20'
  entrypoint: './terraform/deploy.sh'
  env:
    - TF_VAR_source_repo_sha=$COMMIT_SHA
    - ENVIRONMENT=development
images:
- 'gcr.io/$PROJECT_ID/ratelimiter:$SHORT_SHA'